TILE_NULL = 0;
TILE_GROUND = 1;
TILE_COLLISION = 2;
TILE_BREAKABLE = 3;

LIQUID_WATER = 1;
LIQUID_LAVA = 2;

RAMP_STEEP_RIGHT = 1;
RAMP_STEEP_LEFT = 2;

OBJECT_BOULDER = 1;
OBJECT_CHAIN = 2;

CHARACTER_PLAYER = 1;
CHARACTER_BLOB = 2;
CHARACTER_BLACKSMITH = 3;
CHARACTER_BLOBPET = 4;
CHARACTER_WORMBOSS = 5;


CATEGORY_SWORD = 0x0001;
CATEGORY_NON_BODY = 0x0002;
CATEGORY_BODY = 0x0004;
CATEGORY_DEFAULT = 0x0008;

MASK_SWORD = CATEGORY_NON_BODY | CATEGORY_SWORD | CATEGORY_BODY | CATEGORY_DEFAULT;
MASK_NON_BODY = CATEGORY_BODY | CATEGORY_SWORD;
MASK_BODY = CATEGORY_SWORD | CATEGORY_NON_BODY;
MASK_DEFAULT = CATEGORY_SWORD;
