res.test={
    "grid": [
        [
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            }
        ],
        [
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            },
            {
                "collision": true
            }
        ],
        [
            {},
            {
                "blob": true
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {
                "player": true
            }
        ],
        [
            {},
            {
                "blob": true
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {
                "player": true
            }
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ]
    ],
    "metadata": {
        "files": [
            "test_blob.png",
            "test_player.png",
            "test_collision.png"
        ],
        "map_name": "test",
        "tile_size": 80
    }
}